### PR TITLE
Change Railties version dependency to be compatible with Rails 5

### PR DESCRIPTION
**Pull request by pomartel**

### CODE REVIEW

**Comment by ekosz** [comment]
Hey @pomartel, thanks for the PR! Do you happen to know why CI is failing to install the gems now?

**Comment by pomartel** [comment]
I think that's because [Rails 5 requires Ruby 2.2.2+](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#ruby-2-2-2-required) and the travis CI is testing against Ruby 1.9.3, 2.0.0 and 2.1.

**Comment by edlebert** [comment]
It would be awesome if you could merge this. :) :) :) Rails 5 has been out a while now and this is preventing the upgrade.

**Comment by ekosz** [comment]
Okay. I just released version 2.0.0 which now has a minimum ruby version of 2.2.0 and allows for rails 5. Please try it out and let me know what you think!

**Pull request closed without merging**
